name: build-docker-image

on:
  workflow_dispatch:
  push:
    paths:
      - 'software/**'
      - '.github/workflows/docker-image.yml'

jobs:
  docker:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: software
    permissions:
      id-token: write
      packages: write
      contents: write
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
      - 
        name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'pnpm'
          cache-dependency-path: "**/pnpm-lock.yaml"
      -
        name: Build software
        run: |
          pnpm install
          pnpm run build
          
      - 
        name: Create standalone package
        run: |
          mkdir -p standalone-package
          cp -r .next/standalone/* standalone-package/
          cp -r public standalone-package/ || echo "no public folder found"
          mkdir -p standalone-package/.next
          cp -r .next/static standalone-package/.next/ || echo "no static folder found"
          cp .env.example standalone-package/ || echo "no .env files found"
          
          echo '#!/bin/bash
          node server.js' > standalone-package/start.sh
          chmod +x standalone-package/start.sh
          
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          PACKAGE_NAME="release-standalone-$TIMESTAMP-${{ github.sha }}.tar.gz"
          cd standalone-package && tar -czf ../"$PACKAGE_NAME" .
      
      - 
        name: PrepareReg Names
        run: |
          echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:software"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
            
      - 
        name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }} - $(date +%Y-%m-%d-%H-%M-%S)
          tag_name: release-${{ github.sha }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: software/*.tar.gz
          body: |
            # Release for branch: ${{ github.ref_name }}
            **Release Time**: $(date +%Y-%m-%d %H:%M:%S)
            **Commit SHA**: ${{ github.sha }}
            
            ## Docker Image
            Available at: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}`
            
            ## Next.js Standalone Package
            Included in this release as `${{ github.ref_name }}-${{ github.sha }}.tar.gz`
            To run the package, extract it and run `./start.sh` in the terminal.