name: lint and test

on:
  workflow_dispatch:
  push:

jobs:
  Cypress:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: software
    permissions:
      id-token: write
      packages: write
      contents: write
      attestations: write
    env:
      DATABASE_URL: "file:./dev.db"
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - 
        name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: "**/pnpm-lock.yaml"
      - 
        name: Cache next.js build
        uses: actions/cache@v4
        with:
          # See here for caching with `yarn`, `bun` or other package managers https://github.com/actions/cache/blob/main/examples.md or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: |
            ${{ github.workspace }}/software/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - 
        name: Install dependencies
        run: pnpm install
      -
        name: Setup prisma db
        run: pnpm run build:test
          
      - 
        name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: software/
          start: pnpm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: ${{ github.workspace }}/software/cypress/videos
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: ${{ github.workspace }}/software/cypress/screenshots
  Lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: software
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - 
        name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: "**/pnpm-lock.yaml"
      - 
        name: Lint check
        run: |
          pnpm install
          pnpm run lint
  Vitest:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: software
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - 
        name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: "**/pnpm-lock.yaml"
      - 
        name: Cache next.js build
        uses: actions/cache@v4
        with:
          # See here for caching with `yarn`, `bun` or other package managers https://github.com/actions/cache/blob/main/examples.md or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: |
            ${{ github.workspace }}/software/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - 
        name: Vitest run
        run: |
          pnpm install
          pnpm test --run